### ISSUE TITLE
How to enable HTTPS?

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/kenzie.design#2]
<img width="756" alt="Screen Shot 2020-04-21 at 5 03 31 PM" src="https://user-images.githubusercontent.com/19557909/79913765-2556ef00-83f2-11ea-8fe9-193ca15301f1.png">

Hi @thomasjbradley 😄 
I hope the start of the summer is treating you well.

How do I enable HTTPS for my site?

Cheers!
MacKenzie

**Comment by thomasjbradley** [comment]
There is no perfect way to get HTTPS working on GitHub Pages.
Did you hook your domain up using CloudFlare?

**Comment by MacKenzieRose** [comment]
Yessir! 

I take it I need to adjust my settings in Cloudflare?

**Comment by thomasjbradley** [comment]
Yeah, there’s a setting in CloudFlare to make HTTPS the default.

The only problem is that it’s not true HTTPS. The connection between user and CloudFlare is encrypted but not CloudFlare and GitHub. Because GitHub doesn’t currently support HTTPS for custom domain.

**Comment by MacKenzieRose** [comment]
Really? I will see what I can find in CloudFlare for the time being, but that's both interesting and unfortunate to learn.  

In the event that someday I wanted true HTTPS, where would you recommend I host my code to do that?

**Comment by thomasjbradley** [comment]
You could host on Netlify, like we did for the pattern libraries. You’d get full HTTPS support, custom domains, etc. They even have some really cool form features.

**Comment by MacKenzieRose** [comment]
Hi @thomasjbradley 

So I'm in the process of migrating from Cloudflare to Netlify, and I enabled IPv6 support. It doesn't look like I can easily undo that action (at least not without assistance from Netlify's end) and I am intermittently getting the following error message from Github:

<img width="914" alt="Screen Shot 2020-10-16 at 6 14 35 PM" src="https://user-images.githubusercontent.com/19557909/96346320-b7b61380-1060-11eb-9b1d-bf59d4d61a41.png">

Is this likely to cause major problems going forwards?

**Comment by thomasjbradley** [comment]
Probably not an Issue if you’re moving to host on Netlify—that error will eventually not really matter.
